# Uncomment the next line to define a global platform for your project
 platform :ios, '12.2'

target 'MeliProducts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.8.0'
  pod 'SnapKit', '~> 5.0.0'

  target 'MeliProductsTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end
